import LegalLayout from "@/components/LegalLayout"

const sections = [
  ["1. Responsable del tratamiento", <>El responsable del tratamiento es <strong>Arquetipo</strong>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rerum labore nesciunt porro sequi animi neque minima corrupti deserunt autem perspiciatis distinctio soluta, dolorem praesentium quibusdam, vitae possimus sunt ea? Vitae?<strong>ArquetipoTienda@gmail.com</strong>.</>],
  ["2. Datos que tratamos", "Podemos tratar datos de identificación y contacto (nombre, documento, correo, teléfono y dirección), datos de cuenta, historial de pedidos, pagos e interacciones de servicio. No solicitamos datos sensibles. No recolectamos deliberadamente datos de niños, niñas o adolescentes; si fuese necesario, se requerirá la autorización de su representante legal y se respetarán sus derechos prevalentes."],
  ["3. Finalidades", "Usamos los datos para crear y administrar la cuenta; procesar, facturar, entregar y rastrear pedidos; atender garantías, retractos y PQR; prevenir fraude; cumplir obligaciones legales, contables y tributarias; proteger la seguridad del sitio; y enviar comunicaciones necesarias de la compra. Las comunicaciones comerciales o de marketing requieren autorización previa, expresa e informada y pueden cancelarse en cualquier momento."],
  ["4. Autorización y base de tratamiento", "Al proporcionar datos y aceptar esta política, el titular autoriza el tratamiento para las finalidades informadas. La autorización se conserva como prueba. No será exigida cuando exista una excepción legal. El titular puede revocarla o solicitar la supresión cuando proceda; ello no afecta tratamientos necesarios para obligaciones legales o contractuales vigentes."],
  ["5. Derechos del titular", "El titular puede conocer, actualizar, rectificar y suprimir sus datos; solicitar prueba de la autorización; ser informado sobre su uso; revocar la autorización cuando proceda; presentar quejas ante la Superintendencia de Industria y Comercio; y acceder gratuitamente a sus datos. Estos derechos se ejercen por el canal indicado en esta política."],
  ["6. Consultas, reclamos y tiempos", "La solicitud debe identificar al titular, describir el requerimiento y aportar los documentos necesarios. Las consultas se responderán en máximo diez (10) días hábiles, prorrogables por cinco (5) días hábiles adicionales cuando se informe la causa. Los reclamos se atenderán en máximo quince (15) días hábiles, prorrogables por ocho (8) días hábiles adicionales, conforme a la Ley 1581 de 2012 y sus normas reglamentarias."],
  ["7. Encargados, transferencias y seguridad", "Podemos compartir datos estrictamente necesarios con proveedores que actúan como encargados, por ejemplo alojamiento tecnológico, autenticación, pagos, mensajería, correo y transportadoras. Exigimos tratamiento conforme a nuestras instrucciones y medidas de seguridad. Si hay transferencia internacional, se aplicarán las salvaguardas y requisitos exigidos por la normativa colombiana. Adoptamos medidas administrativas, técnicas y físicas razonables para evitar acceso, alteración, pérdida o uso no autorizado."],
  ["8. Conservación", "Conservaremos los datos solo durante el tiempo necesario para las finalidades descritas, la relación comercial y los términos legales, contables, tributarios o de defensa de derechos aplicables. Luego se eliminarán, anonimizarán o bloquearán de forma segura cuando corresponda."],
  ["9. Cookies", "El sitio puede usar cookies técnicas necesarias para mantener sesión, seguridad y funcionamiento. Cualquier cookie no esencial, como analítica o publicidad, requerirá información y autorización cuando la ley lo exija. La persona usuaria puede gestionar cookies desde su navegador, teniendo en cuenta que algunas funciones podrían verse afectadas."],
  ["10. Vigencia y cambios", "Esta política rige desde el 16 de agosto de 2026. Los cambios sustanciales se informarán por los canales adecuados antes de aplicarse cuando la ley lo requiera. Se aplican la Ley 1581 de 2012, el Decreto 1074 de 2015 y las normas colombianas concordantes."],
]

export default function PrivacidadPage() {
  return <LegalLayout eyebrow="Tus datos, bajo control" title="Política de privacidad" intro="Así tratamos y protegemos tu información personal en Arquetipo.">
    {sections.map(([title, text]) => <section key={title as string} className="border-b border-white/10 py-8 last:border-0"><h2 className="text-xl font-bold text-white">{title}</h2><div className="mt-3 max-w-3xl text-sm leading-7 text-zinc-300">{text}</div></section>)}
  </LegalLayout>
}
