import LegalLayout from "@/components/LegalLayout"

const sections = [
  ["1. Identificación del proveedor", <>Este sitio es operado por <strong>Arquetipo</strong> (en adelante, “Arquetipo” o la “Tienda”). Antes de publicar esta página debe completarse y mantenerse visible la razón social o nombre del comerciante, NIT o cédula, domicilio físico, correo electrónico y teléfono de atención. Esta información identifica al proveedor conforme al Estatuto del Consumidor.</>],
  ["2. Alcance y aceptación", "Estos términos regulan la navegación, registro y compra de prendas y accesorios a través de la Tienda. Al crear una cuenta o realizar un pedido, la persona consumidora declara haber leído y aceptado estos términos y la Política de Privacidad. No limitan ni sustituyen los derechos irrenunciables reconocidos por la ley colombiana."],
  ["3. Información de productos y precios", "Cada producto informa sus características esenciales, talla, material, precio en pesos colombianos, disponibilidad y condiciones relevantes antes de la compra. Las imágenes son de referencia y pueden presentar variaciones razonables de color según la pantalla. El precio y los costos de envío aplicables se mostrarán antes de confirmar el pedido. Los errores evidentes de digitación serán corregidos antes de aceptar la orden, informando oportunamente a la persona consumidora."],
  ["4. Formación del contrato y pago", "El pedido constituye una solicitud de compra. La Tienda confirmará su recepción y, cuando corresponda, la aceptación y el pago por el canal registrado. La transacción no se entenderá aceptada si no hay disponibilidad, autorización de pago o verificación razonable para prevenir fraude; en tal caso se informará al cliente y se reversará cualquier cobro realizado. Los comprobantes y comunicaciones electrónicas se conservarán en los términos legales aplicables."],
  ["5. Entrega, envío y seguimiento", "La Tienda informará el plazo, costo, cobertura y modalidad de entrega antes de finalizar la compra. El pedido será enviado a la dirección suministrada por el cliente, quien debe verificar que sea completa y correcta. Cuando exista guía, se comunicará la transportadora y el número de seguimiento. Si hay un retraso atribuible a la Tienda, se informará y se ofrecerán las alternativas legalmente procedentes, incluido el reembolso cuando corresponda."],
  ["6. Derecho de retracto", "En ventas a distancia, el consumidor puede ejercer el derecho de retracto dentro de los cinco (5) días hábiles siguientes a la entrega del bien, en los casos previstos por el artículo 47 de la Ley 1480 de 2011. El producto debe devolverse en condiciones aptas para su comercialización y el consumidor asume los costos de devolución, salvo que la ley disponga otra cosa. No aplica en las excepciones legales, entre ellas bienes confeccionados conforme a especificaciones del consumidor o claramente personalizados. El reembolso se realizará dentro de los plazos legales aplicables después de cumplidas las condiciones de devolución."],
  ["7. Garantía legal y cambios", "La garantía legal cubre la calidad, idoneidad, seguridad y buen estado de los productos en los términos de la Ley 1480 de 2011. El consumidor puede presentar una reclamación por los canales de atención indicando el número de pedido, descripción y evidencia del caso. Los cambios voluntarios por talla, color o gusto están sujetos a disponibilidad y a las condiciones previamente informadas; esta política comercial nunca reemplaza ni reduce la garantía legal o el derecho de retracto."],
  ["8. Reversión del pago", "En compras pagadas mediante mecanismos electrónicos, el consumidor podrá solicitar la reversión del pago en los eventos y siguiendo el procedimiento previstos en el artículo 51 de la Ley 1480 de 2011 y el Decreto 1074 de 2015, entre otros: fraude, operación no solicitada, producto no recibido, producto no conforme o defecto. La solicitud debe presentarse ante la Tienda y el emisor del instrumento de pago dentro del término legal."],
  ["9. Atención de peticiones y reclamos", <>Para solicitudes, PQR, garantía, retracto o reversión, escriba a <strong>ArquetipoTienda@gmail.com</strong> e incluya nombre, documento, número de pedido, medio de respuesta y descripción de la solicitud. La Tienda responderá dentro de los términos legales. El consumidor también puede acudir a la Superintendencia de Industria y Comercio cuando sea procedente.</>],
  ["10. Uso del sitio", "La persona usuaria debe suministrar información veraz, proteger sus credenciales y usar el sitio de forma lícita. No podrá interferir con su seguridad, realizar compras fraudulentas ni usar contenidos de la Tienda sin autorización. La propiedad intelectual de las marcas, imágenes, diseños y contenidos pertenece a sus titulares; su uso no autorizado está prohibido."],
  ["11. Ley aplicable y vigencia", "Estos términos se rigen por las leyes de la República de Colombia, en particular la Ley 1480 de 2011, la Ley 527 de 1999 y las normas que las modifiquen o reglamenten. Cualquier modificación se publicará en esta página y no afectará derechos ya consolidados. Vigencia: 16 de agosto de 2026."],
]

export default function TerminosPage() {
  return <LegalLayout eyebrow="Compra con confianza" title="Términos y condiciones" intro="Reglas claras para comprar prendas y accesorios en Arquetipo.">
    {sections.map(([title, text]) => <section key={title as string} className="border-b border-white/10 py-8 last:border-0"><h2 className="text-xl font-bold text-white">{title}</h2><div className="mt-3 max-w-3xl text-sm leading-7 text-zinc-300">{text}</div></section>)}
  </LegalLayout>
}
